-- Aggiungo tutti i giocatori della lista
INSERT INTO players (first_name, last_name, jersey_number, position, status) VALUES
('Alessio', 'Argenti', 18, 'Centrocampista Centrale', 'active'),
('Alessio', 'Iervolino', 19, NULL, 'active'),
('Matteo', 'Medile', 20, NULL, 'active'),
('Marco', 'Pitingolo', 21, 'Attaccante', 'active'),
('Alessandro', 'Contu', 22, 'Difensore Centrale', 'active'),
('Marco', 'Azzi', 23, 'Difensore Centrale', 'active'),
('Jacopo', 'D''Astolto', 24, 'Centrocampista Difensivo', 'active'),
('Giacomo', 'Caggiano', 25, 'Esterno Destro', 'active'),
('Mario', 'Bervicato', 26, NULL, 'active'),
('Luigi', 'Russo', 27, 'Difensore Centrale', 'active'),
('Vito', 'Tessitore', 28, NULL, 'active'),
('Raffaele', 'Lanzaro', 29, NULL, 'active'),
('Riccardo', 'Perna', 30, NULL, 'active'),
('Nicola', 'Leuci', 31, NULL, 'active'),
('Nathan', 'Habib', 32, NULL, 'active'),
('Matteo', 'Cascone', 33, NULL, 'active'),
('Lucio', 'De Crescenzo', 34, NULL, 'active'),
('Gianmichele', 'Cossu', 35, NULL, 'active'),
('Daniele', 'Moscato', 36, NULL, 'active'),
('Andrea', 'Argenti', 37, 'Esterno Sinistro', 'active'),
('Alessandro', 'Rossi', 38, NULL, 'active'),
('Maurizio', 'Liguori', 39, NULL, 'active');