// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjgzvogrvvsejytqafih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZ3p2b2dydnZzZWp5dHFhZmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Nzc1NDEsImV4cCI6MjA2OTU1MzU0MX0.04zXdZ_uvN4NiUjmrT6gXRt1C_GM3znok-pR7MdzXaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});